// <auto-generated />
using System;
using AiTodoApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiTodoApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423130929_InitialUserAndAppointments")]
    partial class InitialUserAndAppointments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AiTodoApp.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Engineering sync for sprint updates.",
                            EndTime = new DateTime(2026, 4, 25, 10, 30, 0, 0, DateTimeKind.Utc),
                            Profile = "Engineering",
                            Source = 1,
                            StartTime = new DateTime(2026, 4, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            Title = "Weekly Standup",
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Discuss open action items from client notes.",
                            EndTime = new DateTime(2026, 4, 26, 15, 0, 0, 0, DateTimeKind.Utc),
                            Profile = "Product",
                            Source = 3,
                            StartTime = new DateTime(2026, 4, 26, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Title = "Client Requirement Review",
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        });
                });

            modelBuilder.Entity("AiTodoApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GoogleAccountEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("GoogleCalendarId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("GoogleRefreshToken")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime?>("GoogleTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGoogleConnected")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Email = "user1@meetingsplus.local",
                            FullName = "Demo User One",
                            GoogleAccountEmail = "user1@gmail.com",
                            GoogleCalendarId = "primary",
                            GoogleRefreshToken = "seed-refresh-token-user-1",
                            GoogleTokenExpiresAt = new DateTime(2027, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsGoogleConnected = true,
                            Password = "Anubhab*1997",
                            TimeZone = "Asia/Kolkata"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Email = "user2@meetingsplus.local",
                            FullName = "Demo User Two",
                            IsGoogleConnected = false,
                            Password = "Meeting@123",
                            TimeZone = "UTC"
                        });
                });

            modelBuilder.Entity("AiTodoApp.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("AiTodoApp.Domain.Entities.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiTodoApp.Domain.Entities.User", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
